title: Xiangchao Wen's Homepage
page-top-title: Xiangchao Wen
top-section-bg-text: Computer Science
home-subtitle: Xiangchao Wen&ensp;|&ensp;温翔超
copyright-text: '&copy; Xiangchao Wen 2023-2024. All Rights Reserved.'
